server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.102.219:3306/yh_community?characterEncoding=utf-8&useSSL=false
    username: yh_test
    password: yh_test
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
    # 指定全局配置文件位置
    config-location: classpath:mybatis/mybatis-config.xml
    # 指定sql映射文件位置
    mapper-locations: classpath:mybatis/mapper/*.xml